name: Enhancement Request
description: Suggest an improvement or new feature
title: "[Enhancement]: "
labels:
  - enhancement

body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the improvement or feature request.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this improvement be useful?