#!/usr/bin/env python3
"""lint_docs.py -- pre-publish guards for the Wyrd docs.

Two checks, both cheap and both catching real, specific failure modes:

  1. No Obsidian-only link syntax. `[[wikilinks]]` and `![[embeds]]` render in
     Obsidian but break on the static site (and on GitHub). The docs use plain
     relative Markdown links by convention; this guard stops the Obsidian
     syntax from leaking in when you edit there.

  2. Normative specs carry a status/instability marker. A document that uses
     RFC 2119 language (MUST / SHOULD / MAY as standalone words) is normative
     and MUST present as the versioned, possibly-unstable spec it is -- the
     chunk-format spec is published as an explicit DRAFT. This guard fails if
     such a file lacks a `Status:` line together with a version/stability word.

Both scans ignore content inside fenced code blocks, inline code, and HTML
comments, so documenting the syntax (e.g. "write `[[Page]]` in Obsidian") or a
code sample never trips the linter -- the same care the wiki/ tooling takes.

Usage:
    python3 docs/publishing/tools/lint_docs.py             # docs/ is the default root
    python3 docs/publishing/tools/lint_docs.py --docs-root docs
    python3 docs/publishing/tools/lint_docs.py --warn-only # report but exit 0
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

GENERATED_MARKER = "GENERATED by docs/publishing/tools/gen_summary.py"

WIKILINK_RE = re.compile(r"(?<!!)\[\[[^\]]+\]\]")
EMBED_RE = re.compile(r"!\[\[[^\]]+\]\]")
INLINE_CODE_RE = re.compile(r"`[^`]*`")
HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
RFC2119_RE = re.compile(r"\b(MUST|SHOULD|MAY)\b")
STATUS_RE = re.compile(r"Status:", re.IGNORECASE)
STABILITY_RE = re.compile(r"\b(draft|unstable|stable|v\d+|version)\b", re.IGNORECASE)

FENCE_RE = re.compile(r"^\s*(```|~~~)")


def scannable_lines(text: str) -> list[tuple[int, str]]:
    """Yield (1-based line number, line) for lines outside fenced code blocks,
    with inline code spans and HTML comments blanked out so patterns inside
    them are never matched."""
    text = HTML_COMMENT_RE.sub(" ", text)
    out: list[tuple[int, str]] = []
    in_fence = False
    for i, line in enumerate(text.splitlines(), start=1):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        out.append((i, INLINE_CODE_RE.sub(" ", line)))
    return out


def check_wikilinks(path: Path, rel: str) -> list[str]:
    errors = []
    for lineno, line in scannable_lines(path.read_text(encoding="utf-8")):
        if EMBED_RE.search(line):
            errors.append(f"{rel}:{lineno}: Obsidian embed ![[...]] -- "
                          f"use a Markdown image/link instead")
        elif WIKILINK_RE.search(line):
            errors.append(f"{rel}:{lineno}: Obsidian wikilink [[...]] -- "
                          f"use a relative Markdown link instead")
    return errors


def check_spec_status(path: Path, rel: str) -> list[str]:
    """A spec under specs/ that speaks in RFC 2119 terms must announce its
    status and stability."""
    if not rel.startswith("design/specs/"):
        return []
    text = path.read_text(encoding="utf-8")
    body = "\n".join(line for _, line in scannable_lines(text))
    if not RFC2119_RE.search(body):
        return []  # not a normative document (e.g. a plain README)
    has_status = bool(STATUS_RE.search(text))
    has_stability = bool(STABILITY_RE.search(text))
    if has_status and has_stability:
        return []
    return [f"{rel}: normative spec is missing a status/stability marker "
            f"(expected a 'Status:' line and a version/stability word such as "
            f"'DRAFT' or 'v1')"]


def main() -> None:
    ap = argparse.ArgumentParser(description="Lint the Wyrd docs before publish.")
    ap.add_argument(
        "--docs-root",
        default=str(Path(__file__).resolve().parent.parent.parent),
        help="Path to the docs/ directory (default: two levels above "
             "publishing/tools/, i.e. docs/).",
    )
    ap.add_argument("--warn-only", action="store_true",
                    help="Report problems but exit 0.")
    args = ap.parse_args()

    docs_root = Path(args.docs_root).resolve()
    if not docs_root.is_dir():
        sys.exit(f"lint_docs: not a directory: {docs_root}")

    errors: list[str] = []
    for md in sorted(docs_root.rglob("*.md")):
        rel = md.relative_to(docs_root).as_posix()
        if rel == "SUMMARY.md" or rel.startswith("publishing/"):
            continue
        if GENERATED_MARKER in md.read_text(encoding="utf-8"):
            continue
        errors += check_wikilinks(md, rel)
        errors += check_spec_status(md, rel)

    if not errors:
        print("lint_docs: OK")
        return

    label = "WARNING" if args.warn_only else "ERROR"
    for e in errors:
        print(f"lint_docs: {label}: {e}", file=sys.stderr)
    print(f"\nlint_docs: {len(errors)} problem(s) found.", file=sys.stderr)
    sys.exit(0 if args.warn_only else 1)


if __name__ == "__main__":
    main()
