#!/usr/bin/env python3
"""render_site.py -- render the Wyrd docs into the static getwyrd.dev site.

The wyrd repo is the single source of truth: documentation is hand-written
Markdown under `docs/` (the same files edited in Obsidian); the landing page is
authored as structured content in `docs/index.yml`. This script renders that
into the bespoke hand-rolled HTML site -- the paper/Norn aesthetic defined by
`docs/publishing/site/assets/style.css` and the page chrome in
`docs/publishing/templates/` (`page.html` for docs, `home.html` for the
full-bleed landing). The whole site (landing + docs) is what
CI publishes to the getwyrd.dev repo's `main` branch (see docs.yml); getwyrd.dev
is a generated mirror, not hand-edited.

Output structure (served at the apex domain getwyrd.dev):

    /                          docs/index.yml (structured content) rendered
                               through templates/home.html, the full-bleed
                               bespoke landing template
    /docs/                     docs/design/README.md             (docs hub)
    /architecture/             generated index + the numbered docs
    /architecture/<nn>-*.html  docs/design/architecture/<nn>-*.md
    /architecture/diagrams/    generated index + a page per *.mermaid
    /adr/                      docs/design/adr/README.md (it is the index)
    /adr/<nnnn>-*.html         docs/design/adr/<nnnn>-*.md
    /specs/                    generated index
    /specs/**/*.html           docs/design/specs/**/*.md
    /proposals/                docs/design/proposals/README.md + generated list
    /proposals/**/*.html       docs/design/proposals/**/*.md
    /name.html                 docs/NAME.md

Design notes:
  * Deterministic: same tree in, same site out.
  * Link rewriting: relative Markdown links between docs (`.md` / `.mermaid`,
    `design/`-rooted) are resolved to their output URLs. The `--check` pass then
    fails the build on any dangling local link (the linkcheck guarantee mdBook
    used to give us).
  * Diagrams as code: `architecture/diagrams/*.mermaid` are the authority; each
    renders client-side via a vendored mermaid.min.js (no runtime CDN), fetched
    into the build at build time so it is never committed to the source repo.

Usage:
    python3 docs/publishing/tools/render_site.py            # build -> ./build
    python3 docs/publishing/tools/render_site.py --check    # build + fail on dangling links
    python3 docs/publishing/tools/render_site.py -o /tmp/out
"""

from __future__ import annotations

import argparse
import html
import os
import re
import shutil
import sys
import urllib.request
from pathlib import Path

import yaml
from markdown_it import MarkdownIt
from markdown_it.common.utils import escapeHtml

# --- locations (this file is docs/publishing/tools/render_site.py) -----------
TOOLS = Path(__file__).resolve().parent
PUBLISHING = TOOLS.parent
DOCS_ROOT = PUBLISHING.parent
REPO_ROOT = DOCS_ROOT.parent
SITE_DIR = PUBLISHING / "site"
TEMPLATE = PUBLISHING / "templates" / "page.html"
HOME_TEMPLATE = PUBLISHING / "templates" / "home.html"
HOME_DATA = DOCS_ROOT / "index.yml"

# Pinned so the published site is reproducible; fetched at build time into the
# output (build/ is git-ignored), never committed to this repo.
MERMAID_VERSION = "11.4.1"
MERMAID_URL = f"https://cdn.jsdelivr.net/npm/mermaid@{MERMAID_VERSION}/dist/mermaid.min.js"

# Human label per document class, shown in the page's doc-header.
SECTION_CLASS = {
    "architecture": "Architecture",
    "specs": "Specification",
    "adr": "Architecture Decision Record",
    "proposals": "Enhancement Proposal",
}
SECTION_TITLE = {
    "architecture": "Architecture",
    "specs": "Specifications",
    "adr": "Decision Records",
    "proposals": "Enhancement Proposals",
}
SECTION_ORDER = ["architecture", "specs", "adr", "proposals"]

GENERATED_MARKER = "GENERATED by docs/publishing/tools"
_FRONTMATTER_RE = re.compile(r"^---\n.*?\n---\n", re.DOTALL)
_H1_RE = re.compile(r"^#\s+(.+?)\s*$")
_NUM_RE = re.compile(r"^(\d+)")
_MD_LINK_RE = re.compile(r"\]\(([^)]+\.(?:md|mermaid))[)#]")
_INLINE_FMT_RE = re.compile(r"[*_`\[\]]")


# --- small helpers (shared shape with the retired gen_summary.py) ------------

def strip_frontmatter(text: str) -> str:
    return _FRONTMATTER_RE.sub("", text, count=1)


def parse_frontmatter(text: str) -> dict:
    """Parse a leading YAML frontmatter block into a dict (empty if none/invalid)."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    try:
        data = yaml.safe_load(m.group(1))
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def doc_meta_html(fm: dict) -> str:
    """A '.doc-meta' line built from frontmatter (status, date); '' if neither."""
    bits = []
    if fm.get("status"):
        bits.append(f"Status: {html.escape(str(fm['status']))}")
    when = fm.get("created") or fm.get("date")
    if when:
        bits.append(html.escape(str(when)))
    return " · ".join(bits)


def read_title(text: str, fallback: str) -> str:
    for line in strip_frontmatter(text).splitlines():
        m = _H1_RE.match(line)
        if m:
            return m.group(1).strip()
    return fallback


def numeric_key(name: str):
    m = _NUM_RE.match(name)
    return (int(m.group(1)) if m else 9999, name)


def prettify(stem: str) -> str:
    out = []
    for word in stem.replace("_", " ").replace("-", " ").split():
        out.append(word.upper() if word.lower() == "c4" else word.capitalize())
    return " ".join(out)


def mermaid_description(text: str) -> str:
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("%%"):
            return s.lstrip("% ").strip()
    return ""


def description_of(text: str) -> str:
    """First real paragraph, flattened to plain text for the meta description."""
    body = strip_frontmatter(text)
    for raw in body.splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ">", "-", "*", "|", "```", "<")):
            continue
        plain = _INLINE_FMT_RE.sub("", re.sub(r"\(([^)]*)\)", "", line))
        plain = re.sub(r"\s+", " ", plain).strip(" .")
        if plain:
            return (plain[:177] + "...") if len(plain) > 180 else plain
    return "Wyrd documentation."


# --- output-URL model --------------------------------------------------------

def out_url(rel: str) -> str | None:
    """Map a docs-relative source path (posix) to its site-absolute URL, or None
    if the file is not published."""
    if rel == "NAME.md":
        return "/name.html"
    if rel == "design/README.md":
        return "/docs/"
    if not rel.startswith("design/"):
        return None  # docs/README.md (GitHub-facing) and anything else: unpublished
    rest = rel[len("design/"):]
    if rest.startswith("templates/"):
        return None  # authoring scaffolding (ADR/proposal/architecture), not published
    if rest.endswith("README.md"):
        d = rest[: -len("README.md")].rstrip("/")
        return f"/{d}/" if d else "/docs/"
    if rest.endswith(".mermaid"):
        return f"/{rest[:-len('.mermaid')]}.html"
    if rest.endswith(".md"):
        return f"/{rest[:-3]}.html"
    return None


def url_to_path(out: Path, url: str) -> Path:
    """Filesystem path under the output dir for a site-absolute URL."""
    if url.endswith("/"):
        return out / url.strip("/") / "index.html"
    return out / url.lstrip("/")


def section_of(url: str) -> str | None:
    parts = [p for p in url.split("/") if p]
    return parts[0] if parts else None


# --- markdown rendering ------------------------------------------------------

def make_md() -> MarkdownIt:
    md = MarkdownIt("gfm-like")
    # gfm-like enables linkify (bare-URL autolinking, as on GitHub/Obsidian),
    # which needs the optional linkify-it-py package. Install
    # `markdown-it-py[linkify]` for it; degrade gracefully without it rather than
    # crashing at parse time.
    try:
        import linkify_it  # noqa: F401
    except ImportError:
        md.disable("linkify")

    def render_fence(self, tokens, idx, options, env):
        tok = tokens[idx]
        if (tok.info or "").strip().lower() == "mermaid":
            env["has_mermaid"] = True
            # Escaped so a diagram containing '<' is valid HTML; the browser
            # decodes textContent back to the raw graph before Mermaid reads it.
            return f'<div class="mermaid">\n{escapeHtml(tok.content)}</div>\n'
        return self.fence(tokens, idx, options, env)

    md.add_render_rule("fence", render_fence)
    return md


def rewrite_links(tokens, src_rel: str, url_map: dict[str, str], dangling: list[str]):
    """Rewrite relative .md/.mermaid links/images in the token stream to their
    output URLs. Records unresolved local targets in `dangling`."""
    src_dir = src_rel.rsplit("/", 1)[0] if "/" in src_rel else ""

    def resolve(href: str) -> str:
        if re.match(r"^[a-z]+:", href) or href.startswith(("//", "#", "mailto:")):
            return href
        target, _, frag = href.partition("#")
        if not target.endswith((".md", ".mermaid")):
            return href
        # normalise the relative path against the source file's directory
        base = src_dir.split("/") if src_dir else []
        for part in target.split("/"):
            if part in ("", "."):
                continue
            if part == "..":
                if base:
                    base.pop()
            else:
                base.append(part)
        key = "/".join(base)
        if key in url_map:
            return url_map[key] + (("#" + frag) if frag else "")
        dangling.append(f"{src_rel} -> {href}")
        return href

    def walk(toks):
        for t in toks:
            if t.type == "link_open":
                h = t.attrGet("href")
                if h is not None:
                    t.attrSet("href", resolve(h))
            elif t.type == "image":
                s = t.attrGet("src")
                if s is not None:
                    t.attrSet("src", resolve(s))
            if t.children:
                walk(t.children)

    walk(tokens)


_TASK_RE = re.compile(r"<li>\[([ xX])\]\s")


def finish_tasklists(html_str: str) -> str:
    def sub(m):
        checked = " checked" if m.group(1).lower() == "x" else ""
        return f'<li class="task"><input type="checkbox" disabled{checked}> '
    return _TASK_RE.sub(sub, html_str)


# --- page assembly -----------------------------------------------------------

class Renderer:
    def __init__(self, out: Path):
        self.out = out
        self.md = make_md()
        self.template = TEMPLATE.read_text(encoding="utf-8")
        self.home_template = HOME_TEMPLATE.read_text(encoding="utf-8")
        self.url_map: dict[str, str] = {}
        self.titles: dict[str, str] = {}   # url -> title
        self.dangling: list[str] = []
        self.needs_mermaid = False
        self.cur_desc = "Wyrd documentation."

    # -- discovery --
    def discover(self) -> list[tuple[str, Path, str]]:
        """Return (rel, path, url) for every published source; populate url_map."""
        sources: list[tuple[str, Path, str]] = []
        candidates = [DOCS_ROOT / "NAME.md", DOCS_ROOT / "design" / "README.md"]
        candidates += sorted((DOCS_ROOT / "design").rglob("*.md"))
        candidates += sorted((DOCS_ROOT / "design").rglob("*.mermaid"))
        for path in candidates:
            rel = path.relative_to(DOCS_ROOT).as_posix()
            url = out_url(rel)
            if url is None:
                continue
            if path.suffix == ".md" and GENERATED_MARKER in path.read_text(encoding="utf-8"):
                continue  # leftover mdBook artifact
            self.url_map[rel] = url
            if rel.endswith(".mermaid"):
                # alias the .md form some prose may still use
                self.url_map[rel[:-len(".mermaid")] + ".md"] = url
            sources.append((rel, path, url))
        # alias for the generated diagrams index, if referenced as .md
        self.url_map["design/architecture/diagrams/index.md"] = "/architecture/diagrams/"
        return sources

    # -- emit one templated page --
    def emit(self, url: str, title: str, content_html: str, doc_class: str,
             has_mermaid: bool, doc_meta: str = ""):
        rows = ""
        if doc_class:
            rows += f'    <p class="doc-class">{html.escape(doc_class)}</p>\n'
        if doc_meta:
            rows += f'    <p class="doc-meta">{doc_meta}</p>\n'
        if rows:
            header = (
                '<div class="wrap">\n  <header class="doc-header">\n'
                + rows
                + "  </header>\n</div>"
            )
        else:
            header = ""
        scripts = ""
        if has_mermaid:
            self.needs_mermaid = True
            scripts = (
                '<script src="/assets/mermaid.min.js"></script>\n'
                "<script>mermaid.initialize({startOnLoad:true,theme:\"neutral\"});</script>"
            )
        page = (
            self.template
            .replace("{{TITLE}}", html.escape(title))
            .replace("{{DESCRIPTION}}", html.escape(self.cur_desc))
            .replace("{{DOC_HEADER}}", header)
            .replace("{{CONTENT}}", content_html)
            .replace("{{SCRIPTS}}", scripts)
        )
        dest = url_to_path(self.out, url)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(page, encoding="utf-8")
        self.titles[url] = title

    def render_markdown(self, rel: str, text: str) -> tuple[str, bool]:
        env: dict = {}
        tokens = self.md.parse(strip_frontmatter(text), env)
        rewrite_links(tokens, rel, self.url_map, self.dangling)
        body = self.md.renderer.render(tokens, self.md.options, env)
        return finish_tasklists(body), bool(env.get("has_mermaid"))

    # -- the bespoke landing page (docs/index.yml -> /) --
    def inline(self, text: str) -> str:
        """Render a single text field's inline Markdown (bold/italic/links/
        entities), with no surrounding <p>. Empty input -> empty string."""
        return self.md.renderInline(text or "").strip()

    def home_content(self, data: dict) -> str:
        """Build the landing body HTML from the structured index.yml content.
        The design (classes, layout) is fixed here + in style.css; index.yml
        only supplies the words."""
        hero = data.get("hero") or {}
        ctas = []
        for c in hero.get("ctas") or []:
            cls = "btn primary" if c.get("primary") else "btn"
            arrow = ' <span class="arr" aria-hidden="true">→</span>' if c.get("arrow") else ""
            ctas.append(f'    <a class="{cls}" href="{html.escape(c["href"])}">'
                        f'{self.inline(c["label"])}{arrow}</a>')
        cta_block = ('  <div class="cta-row">\n' + "\n".join(ctas) + "\n  </div>\n") if ctas else ""
        hero_html = (
            '<div class="wrap">\n  <div class="hero">\n'
            f'    <span class="status"><span class="dot" aria-hidden="true"></span>{self.inline(hero.get("status", ""))}</span>\n'
            '    <hr class="thread-rule">\n'
            f'    <h1>{self.inline(hero.get("title", ""))}</h1>\n'
            f'    <p class="lede">{self.inline(hero.get("lede", ""))}</p>\n'
            f'    <p class="pron">{self.inline(hero.get("pron", ""))}</p>\n'
            f"{cta_block}"
            "  </div>\n</div>\n"
        )

        sections = []
        for s in data.get("sections") or []:
            parts = [f'    <p class="eyebrow">{self.inline(s.get("eyebrow", ""))}</p>',
                     f'    <h2>{self.inline(s.get("heading", ""))}</h2>']
            for para in s.get("body") or []:
                parts.append(f'    <p class="muted">{self.inline(para)}</p>')
            if s.get("props"):
                lis = "\n".join(
                    f'      <li><span class="term">{self.inline(p["term"])}</span>'
                    f'<span class="desc">{self.inline(p["desc"])}</span></li>'
                    for p in s["props"]
                )
                parts.append(f'    <ul class="props">\n{lis}\n    </ul>')
            if s.get("norns"):
                cards = "\n".join(
                    '      <div class="norn">\n'
                    f'        <p class="n-name">{self.inline(n["name"])}</p>\n'
                    f'        <p class="n-gloss">{self.inline(n["gloss"])}</p>\n'
                    f'        <p class="n-role">{self.inline(n["role"])}</p>\n'
                    "      </div>"
                    for n in s["norns"]
                )
                parts.append(f'    <div class="norns">\n{cards}\n    </div>')
            if s.get("note"):
                quote = (f' <span class="quote">{self.inline(s["quote"])}</span>'
                         if s.get("quote") else "")
                parts.append(f'    <p class="name-note">{self.inline(s["note"])}{quote}</p>')
            sections.append("  <section>\n" + "\n".join(parts) + "\n  </section>")
        sections_html = '<div class="wrap">\n' + "\n".join(sections) + "\n</div>\n"

        return hero_html + "\n" + sections_html

    def render_home(self):
        if not HOME_DATA.exists():
            return
        data = yaml.safe_load(HOME_DATA.read_text(encoding="utf-8")) or {}
        meta = data.get("meta") or {}
        title = meta.get("title", "Wyrd")
        desc = meta.get("description", "Wyrd documentation.")
        page = (
            self.home_template
            .replace("{{TITLE}}", html.escape(title))
            .replace("{{DESCRIPTION}}", html.escape(desc))
            .replace("{{OG_TITLE}}", html.escape(meta.get("og_title", title)))
            .replace("{{OG_DESCRIPTION}}", html.escape(meta.get("og_description", desc)))
            .replace("{{CONTENT}}", self.home_content(data))
        )
        dest = self.out / "index.html"
        dest.write_text(page, encoding="utf-8")

    # -- per-source page --
    def render_source(self, rel: str, path: Path, url: str):
        # section-root READMEs and the design hub are built as index pages later
        if rel == "design/README.md" or re.fullmatch(r"design/[^/]+/README\.md", rel):
            return
        text = path.read_text(encoding="utf-8")
        section = section_of(url)
        if rel.endswith(".mermaid"):
            title = prettify(path.stem)
            desc = mermaid_description(text)
            self.cur_desc = desc or f"{title} diagram."
            body = (f"<h1>{html.escape(title)}</h1>\n"
                    + (f"<p>{html.escape(desc)}</p>\n" if desc else "")
                    + f'<div class="mermaid">\n{escapeHtml(text.rstrip())}</div>\n')
            self.emit(url, title, body, "Diagram", has_mermaid=True)
            return
        title = read_title(text, prettify(path.stem))
        self.cur_desc = description_of(text)
        body, has_mermaid = self.render_markdown(rel, text)
        self.emit(url, title, body, SECTION_CLASS.get(section, ""), has_mermaid,
                  doc_meta_html(parse_frontmatter(text)))

    # -- generated list of a section's pages --
    def section_list_html(self, section: str, exclude: set[str]) -> str:
        items = []
        for url, title in self.titles.items():
            if section_of(url) != section or url in exclude:
                continue
            items.append((url, title))
        items.sort(key=lambda it: [numeric_key(p) for p in it[0].strip("/").split("/")])
        if not items:
            return ""
        lis = "\n".join(
            f'    <li><a href="{u}">{html.escape(t)}</a></li>' for u, t in items
        )
        return f"<h2>Documents</h2>\n<ul>\n{lis}\n</ul>\n"

    # -- section index pages (built after all leaf pages exist) --
    def build_indexes(self):
        # /docs/ hub from design/README.md + a sections list
        hub = (DOCS_ROOT / "design" / "README.md").read_text(encoding="utf-8")
        self.cur_desc = description_of(hub)
        hub_body, _ = self.render_markdown("design/README.md", hub)
        sections_li = "\n".join(
            f'    <li><a href="/{s}/">{SECTION_TITLE[s]}</a></li>'
            for s in SECTION_ORDER
        )
        hub_body += f"<h2>Sections</h2>\n<ul>\n{sections_li}\n</ul>\n"
        self.emit("/docs/", read_title(hub, "Documentation"), hub_body, "", False)

        # diagrams index (architecture/diagrams/)
        diagram_urls = {u for u in self.titles if u.startswith("/architecture/diagrams/")}
        if diagram_urls:
            lis = "\n".join(
                f'    <li><a href="{u}">{html.escape(self.titles[u])}</a></li>'
                for u in sorted(diagram_urls)
            )
            self.cur_desc = "Architecture diagrams, kept as Mermaid source."
            body = ("<h1>Diagrams</h1>\n<p>Architecture diagrams kept as Mermaid "
                    "source under <code>design/architecture/diagrams/</code> "
                    "(diagrams as code &mdash; diffable and reviewed in PRs).</p>\n"
                    f"<ul>\n{lis}\n</ul>\n")
            self.emit("/architecture/diagrams/", "Diagrams", body, "", False)

        # one index per document class
        for section in SECTION_ORDER:
            readme = DOCS_ROOT / "design" / section / "README.md"
            url = f"/{section}/"
            exclude = {url}
            if readme.exists():
                text = readme.read_text(encoding="utf-8")
                self.cur_desc = description_of(text)
                body, _ = self.render_markdown(f"design/{section}/README.md", text)
                # append a generated list only when the README has no internal links
                if not _MD_LINK_RE.search(text):
                    body += "\n" + self.section_list_html(section, exclude)
                self.emit(url, read_title(text, SECTION_TITLE[section]), body, "", False)
            else:
                self.cur_desc = f"{SECTION_TITLE[section]} for Wyrd."
                body = (f"<h1>{SECTION_TITLE[section]}</h1>\n"
                        + self.section_list_html(section, exclude))
                self.emit(url, SECTION_TITLE[section], body, "", False)

    # -- static assets + mermaid --
    def copy_site(self):
        for item in SITE_DIR.iterdir():
            dest = self.out / item.name
            if item.is_dir():
                shutil.copytree(item, dest, dirs_exist_ok=True)
            else:
                dest.write_bytes(item.read_bytes())

    def ensure_mermaid(self):
        if not self.needs_mermaid:
            return
        dest = self.out / "assets" / "mermaid.min.js"
        dest.parent.mkdir(parents=True, exist_ok=True)
        # Cache outside the (wiped-each-run) output dir so local rebuilds and CI
        # restores avoid re-downloading. MERMAID_JS env can point at a local file.
        cache = Path(os.environ.get("MERMAID_JS")
                     or REPO_ROOT / ".cache" / f"mermaid-{MERMAID_VERSION}.min.js")
        if not cache.exists():
            cache.parent.mkdir(parents=True, exist_ok=True)
            print(f"render_site: fetching mermaid {MERMAID_VERSION} ...", file=sys.stderr)
            with urllib.request.urlopen(MERMAID_URL) as r:  # noqa: S310 (pinned URL)
                cache.write_bytes(r.read())
        dest.write_bytes(cache.read_bytes())

    # -- link audit --
    def audit(self) -> list[str]:
        broken = []
        attr_re = re.compile(r'(?:href|src)="([^"]+)"')
        for html_file in sorted(self.out.rglob("*.html")):
            base = html_file.parent
            for ref in attr_re.findall(html_file.read_text(encoding="utf-8")):
                target, _, _ = ref.partition("#")
                if not target or re.match(r"^[a-z]+:", target) or target.startswith(("//", "mailto:")):
                    continue
                if target.startswith("/"):
                    p = self.out / target.lstrip("/")
                else:
                    p = base / target
                if target.endswith("/"):
                    p = p / "index.html"
                if not p.exists():
                    broken.append(f"{html_file.relative_to(self.out)} -> {ref}")
        return broken

    # -- orchestration --
    def run(self, check: bool) -> int:
        if self.out.exists():
            shutil.rmtree(self.out)
        self.out.mkdir(parents=True)
        sources = self.discover()
        # pre-register titles so generated lists/indexes can reference any page
        for rel, path, url in sources:
            if rel.endswith(".mermaid"):
                self.titles[url] = prettify(path.stem)
            elif not (rel == "design/README.md"
                      or re.fullmatch(r"design/[^/]+/README\.md", rel)):
                self.titles[url] = read_title(path.read_text(encoding="utf-8"),
                                              prettify(path.stem))
        for rel, path, url in sources:
            self.render_source(rel, path, url)
        self.build_indexes()
        self.render_home()
        self.copy_site()
        self.ensure_mermaid()

        pages = len(list(self.out.rglob("*.html")))
        print(f"render_site: wrote {pages} page(s) to "
              f"{self.out.relative_to(REPO_ROOT) if self.out.is_relative_to(REPO_ROOT) else self.out}")

        if self.dangling:
            for d in sorted(set(self.dangling)):
                print(f"render_site: WARNING unresolved link: {d}", file=sys.stderr)
        if check:
            broken = self.audit()
            for b in broken:
                print(f"render_site: ERROR dangling link in output: {b}", file=sys.stderr)
            if broken or self.dangling:
                print(f"\nrender_site: {len(broken)} dangling output link(s), "
                      f"{len(set(self.dangling))} unresolved source link(s).", file=sys.stderr)
                return 1
            print("render_site: link audit OK")
        return 0


def main() -> None:
    ap = argparse.ArgumentParser(description="Render the Wyrd docs into the static site.")
    ap.add_argument("-o", "--out", default=str(REPO_ROOT / "build"),
                    help="output directory (default: ./build at the repo root)")
    ap.add_argument("--check", action="store_true",
                    help="fail the build on any dangling internal link")
    args = ap.parse_args()
    rc = Renderer(Path(args.out).resolve()).run(args.check)
    sys.exit(rc)


if __name__ == "__main__":
    main()
