//! Conformance-vector definitions and the JSON schema shared by the runner and
//! the generator.
//!
//! The vectors live *with* the spec (`docs/design/specs/conformance/`, ADR-0002)
//! so the reference reader and the spec stay honest with each other in CI. This
//! module owns the `ExpectedFragment` schema (kept here rather than in
//! `chunk-format`, which stays serde-free) and the deterministic definitions the
//! `gen-vectors` subcommand writes out.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};
use wyrd_chunk_format::{
    encode, ChecksumAlgo, DecodedFragment, EcSchemeType, EncryptionScheme, FragmentHeader,
    CORE_HEADER_LEN, FLAG_ENCRYPTED,
};

/// Directory holding valid fragments and their `.expected.json` interpretations.
pub fn valid_dir() -> PathBuf {
    crate::workspace_root().join("docs/design/specs/conformance/vectors/v1")
}

/// Directory holding malformed fragments and their `.reason.txt`.
pub fn invalid_dir() -> PathBuf {
    crate::workspace_root().join("docs/design/specs/conformance/invalid/v1")
}

/// The parsed, verified interpretation a conforming reader must produce for a
/// valid fragment. `chunk_id`/`payload_length` are decimal strings (u128/u64 do
/// not round-trip safely through JSON numbers) and the payload is lowercase hex.
#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExpectedFragment {
    pub format_version: u16,
    pub flags: u8,
    pub checksum_algo: String,
    pub encryption_scheme: String,
    pub ec_scheme_type: String,
    pub ec_k: u8,
    pub ec_m: u8,
    pub ec_fragment_index: u16,
    pub chunk_id: String,
    pub payload_length: String,
    pub payload_hex: String,
}

impl ExpectedFragment {
    /// Project a decoded fragment into the JSON-friendly expected form.
    pub fn from_decoded(decoded: &DecodedFragment) -> Self {
        let h = &decoded.header;
        Self {
            format_version: h.format_version,
            flags: h.flags,
            checksum_algo: checksum_algo_str(h.checksum_algo).to_string(),
            encryption_scheme: encryption_scheme_str(h.encryption_scheme).to_string(),
            ec_scheme_type: ec_scheme_str(h.ec_scheme_type).to_string(),
            ec_k: h.ec_k,
            ec_m: h.ec_m,
            ec_fragment_index: h.ec_fragment_index,
            chunk_id: h.chunk_id.to_string(),
            payload_length: h.payload_length.to_string(),
            payload_hex: to_hex(&decoded.payload),
        }
    }
}

fn checksum_algo_str(a: ChecksumAlgo) -> &'static str {
    match a {
        ChecksumAlgo::Crc32c => "crc32c",
        ChecksumAlgo::Blake3 => "blake3",
    }
}

fn encryption_scheme_str(s: EncryptionScheme) -> &'static str {
    match s {
        EncryptionScheme::None => "none",
    }
}

fn ec_scheme_str(t: EcSchemeType) -> &'static str {
    match t {
        EcSchemeType::None => "none",
        EcSchemeType::Replication => "replication",
        EcSchemeType::ReedSolomon => "reed-solomon",
    }
}

/// Lowercase hex of a byte string.
pub fn to_hex(bytes: &[u8]) -> String {
    use std::fmt::Write;
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        let _ = write!(s, "{b:02x}");
    }
    s
}

/// A valid vector: a name, the header/payload to encode, and the resulting bytes.
pub struct ValidVector {
    pub name: &'static str,
    pub header: FragmentHeader,
    pub payload: Vec<u8>,
}

/// A malformed vector: a name, the bytes, the `FragmentError` variant a reader
/// must reject it with, and a human-readable reason.
pub struct InvalidVector {
    pub name: &'static str,
    pub bytes: Vec<u8>,
    pub expected_variant: &'static str,
    pub reason: &'static str,
}

// Fixed chunk ids so generated bytes are deterministic and reviewable.
const ID_A: u128 = 0x0102_0304_0506_0708_090a_0b0c_0d0e_0f10;
const ID_B: u128 = 0xdead_beef_0000_0000_0000_0000_cafe_babe;

/// The valid vectors landed for v1 (≥1 required; a few for real coverage).
pub fn valid_vectors() -> Vec<ValidVector> {
    let mut replication = FragmentHeader::new_v1(ID_B, 0);
    replication.ec_scheme_type = EcSchemeType::Replication;
    replication.ec_fragment_index = 2;
    let replication_payload = b"replica".to_vec();
    replication.payload_length = replication_payload.len() as u64;

    vec![
        ValidVector {
            name: "empty-payload",
            header: FragmentHeader::new_v1(ID_A, 0),
            payload: Vec::new(),
        },
        ValidVector {
            name: "crc32c-basic",
            header: FragmentHeader::new_v1(ID_A, 11),
            payload: b"hello wyrd\n".to_vec(),
        },
        ValidVector {
            name: "replication-fragment",
            header: replication,
            payload: replication_payload,
        },
    ]
}

/// The malformed vectors landed for v1 (≥1 required). Each is produced from a
/// valid encoding so the corruption under test is the only thing wrong.
pub fn invalid_vectors() -> Vec<InvalidVector> {
    let base = encode(&FragmentHeader::new_v1(ID_A, 7), b"payload");

    let mut bad_magic = base.clone();
    bad_magic[0] ^= 0xff;

    let mut bad_version = base.clone();
    bad_version[4..6].copy_from_slice(&2u16.to_le_bytes());

    // Corrupt a header field without re-stamping the header checksum.
    let mut header_checksum_mismatch = base.clone();
    header_checksum_mismatch[16] ^= 0xff;

    // Corrupt a payload byte; the header stays valid, the payload checksum fails.
    let mut payload_checksum_mismatch = base.clone();
    payload_checksum_mismatch[CORE_HEADER_LEN as usize] ^= 0xff;

    let truncated_header = base[..10].to_vec();

    let mut encrypted = FragmentHeader::new_v1(ID_A, 7);
    encrypted.flags = FLAG_ENCRYPTED;
    let encryption_flag_set = encode(&encrypted, b"payload");

    vec![
        InvalidVector {
            name: "bad-magic",
            bytes: bad_magic,
            expected_variant: "BadMagic",
            reason: "leading bytes are not the WYRD magic",
        },
        InvalidVector {
            name: "bad-version",
            bytes: bad_version,
            expected_variant: "UnsupportedVersion",
            reason: "format_version is 2, which a v1 reader does not understand",
        },
        InvalidVector {
            name: "header-checksum-mismatch",
            bytes: header_checksum_mismatch,
            expected_variant: "HeaderChecksumMismatch",
            reason: "a header byte was altered without updating header_checksum",
        },
        InvalidVector {
            name: "payload-checksum-mismatch",
            bytes: payload_checksum_mismatch,
            expected_variant: "PayloadChecksumMismatch",
            reason: "a payload byte was altered without updating payload_checksum",
        },
        InvalidVector {
            name: "truncated-header",
            bytes: truncated_header,
            expected_variant: "TruncatedHeader",
            reason: "buffer is shorter than the 44-byte core header",
        },
        InvalidVector {
            name: "encryption-flag-set",
            bytes: encryption_flag_set,
            expected_variant: "EncryptedPayloadUnsupported",
            reason: "flags bit 0 is set; a v1 reader must refuse to return the payload",
        },
    ]
}
